CREATE DATABASE act_block_chain;
USE act_block_chain;

CREATE TABLE `tb_act_block` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `block_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '区块hash',
  `block_num` bigint(20) unsigned NOT NULL COMMENT '块号',
  `block_size` bigint(16) unsigned NOT NULL COMMENT '块大小（字节）',
  `previous` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '前一个块块id',
  `trx_digest` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '块中交易的摘要',
  `prev_secret` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '上轮secret',
  `next_secret_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '本轮secret的hash',
  `random_seed` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '随机种子',
  `signee` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产块者',
  `block_time` datetime NOT NULL COMMENT '产块时间',
  `trans_num` int(11) unsigned NOT NULL COMMENT '区块内交易数量',
  `trans_amount` bigint(20) unsigned NOT NULL COMMENT '区块内交易总金额',
  `trans_fee` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '区块内交易总手续费',
  `status` tinyint(4) NOT NULL DEFAULT '0',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `block_id` (`block_id`) USING BTREE,
  KEY `idx_block_num` (`block_num`) USING BTREE,
  KEY `idx_signee` (`signee`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tb_act_transaction` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `trx_id` varchar(64) CHARACTER SET utf8 NOT NULL COMMENT '交易id',
  `block_id` varchar(64) CHARACTER SET utf8 NOT NULL COMMENT '区块hash',
  `block_num` bigint(20) NOT NULL COMMENT '块号',
  `block_position` int(11) NOT NULL COMMENT '交易在块中的位置',
  `trx_type` int(11) NOT NULL DEFAULT '0' COMMENT '0-普通转账,1-代理领工资,2-注册账户,3-注册代理,10-注册合约,11-合约充值,12-合约升级,13-合约销毁,14-调用合约,15-合约出账',
  `coin_type` varchar(70) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_id` varchar(70) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `from_acct` varchar(64) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '发起账号',
  `from_addr` varchar(64) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '发起地址',
  `to_acct` varchar(64) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '接收账号',
  `to_addr` varchar(64) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '接收地址',
  `sub_address` varchar(70) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` bigint(30) unsigned NOT NULL DEFAULT '0' COMMENT '金额',
  `fee` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '手续费,如果是合约交易，包含gas消耗，注册保证金等',
  `memo` text COLLATE utf8mb4_unicode_ci COMMENT '备注',
  `trx_time` datetime NOT NULL COMMENT '交易时间',
  `called_abi` varchar(6000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '调用的合约函数，非合约交易该字段为空',
  `abi_params` varchar(6000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '调用合约函数时传入的参数，非合约交易该字段为空',
  `event_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `event_param` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extra_trx_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '结果交易id,仅针对合约交易',
  `is_completed` tinyint(4) unsigned DEFAULT '0' COMMENT '合约调用结果,0-成功,1- 失败',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `idx_block_id` (`block_id`),
  KEY `idx_block_num` (`block_num`) USING BTREE,
  KEY `idx_from_acct` (`from_acct`) USING BTREE,
  KEY `idx_from_addr` (`from_addr`) USING BTREE,
  KEY `idx_to_acct` (`to_acct`) USING BTREE,
  KEY `idx_to_addr` (`to_addr`) USING BTREE,
  KEY `idx_trx_time` (`trx_time`) USING BTREE,
  KEY `idx_trx_id` (`trx_id`) USING BTREE,
  KEY `idx_ sub_address` (`sub_address`) USING BTREE,
  KEY `idx_contract_id` (`contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
